# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/automated-testing',
                'doc_host': 'https://jit3pam.github.io',
                'git_url': 'https://github.com/jit3pam/automated-testing',
                'lib_path': 'automated_testing'},
  'syms': {'automated_testing.core': {'automated_testing.core.foo': ('core.html#foo', 'automated_testing/core.py')}}}
